bin.includes = plugin.xml,\
               META-INF/,\
               .,\
               icons/,\
               prompts/,\
               css/,\
               js/,\
               fragment.e4xmi,\
               OSGI-INF/l10n/bundle.properties,\
               lib/,\
               lib/jackson-annotations-2.15.0-rc1.jar,\
               lib/jackson-core-2.15.0-rc1.jar,\
               lib/jackson-databind-2.15.0-rc1.jar,\
               lib/tika-parser-text-module-3.3.1.jar
source.. = src/
output.. = bin/
